obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

#ifdef VENDOR_EDIT
#/* Zhangchangan  PSW.BSP.CHG  2019-10-30 */
obj-$(CONFIG_OPPO_SM6125Q_CHARGER)	+= oppo/
#endif